name: Latest articles and videos
on:
  schedule:
    # Runs every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Articles and Videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ARTICLES"
          commit_message: "Updated readme with the latest data"
          max_post_count: 50
          feed_list: "https://dev.to/feed/florianrappl,https://medium.com/feed/@florianrappl,https://microfrontends.hashnode.dev/rss.xml,https://www.youtube.com/feeds/videos.xml?channel_id=UC2vFVYoHTcbuWLt_JANeiWw"
          